### ISSUE TITLE
Support for Auro 3D

### ISSUE THREAD

**Issue by Sonic3R** [UniqProject/BDInfo#31]
It is possible to add support for Auro 3D ? Seems to be likely atmos for Dolby Digital or TrueHD

I will attach sample disc which contains Auro 3D
https://drive.google.com/file/d/1O0WGqsFT4TcSxX2MoxmfCFfrjOFO0eWZ/view?usp=sharing

**Comment by UniqProject** [comment]
Thanks for the sample, I will see what I can do

**Comment by Sonic3R** [comment]
Any progress about this ?

**Comment by UniqProject** [comment]
Hi @Sonic3R 

In the sanple file I could not find any other metadata besides the normal DTS-HD metadata, for both German and English streams.

From what I found out so far, the Auro 3D does not embed any metadata into the streams like Atmos or DTS:X but rather encodes the spatial channel information into the PCM signal before any further compression.

Since there is no metadata carried in the stream, we can't parse it.
As I see it, the only way to detect Auro 3D is by decoding the audio stream with an Auro 3D capable decoder.

Unless I missed some information, there is currently no way this can be implemented.
